name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: production  # Make sure this matches your environment name
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version:  '18'
      
      - name: Install dependencies
        run:  npm install
      
      - name: Build
        run: npm run build
      
      - name:  Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets. GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets. nfp_NHUpYSSAHbifutLFCiaLwRQc2D3bzgy1d428 }}
          NETLIFY_SITE_ID: ${{ secrets.1417ff4f-fa56-4659-b793-4afcd5ba7dd6 }}
        timeout-minutes: 1
